version: '3.1'
services:
  app:
    container_name: springboot-postgres
    image: springboot-postgres
    build: ./
    ports:
    - "8081:8081"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
volumes:
  db_data: